### PR TITLE
Waf module enhancement

### PR DESCRIPTION
**Pull request by NikitaGandhi**
**restructure/refactor/enhance `opendatacube/terraform-aws-waf-owasp-top-10-rules` module** 
- spilt each rules in its own tf file - one rule file for each rule type to support both `regional` or `global`
- Added variables to support rule action type: `ALLOW`, `BLOCK` or `COUNT`
- Updated Example
- Updated Readme

### CODE REVIEW

**Comment by pindge** [comment]
How to test any of this?

**Comment by whatnick** [comment]
> How to test any of this?

Would be testable in `dev` we will have to collect sample notebooks from [dea-notebooks](https://github.com/GeoscienceAustralia/dea-notebooks) and manually make changes and re-save them to see if we trigger any false positives. This is a huge manual test need, perhaps can delegate to rest of DEA for collaborative testing in dev.

**Review by whatnick — APPROVED** [review]
LGTM then test in Dev

**Comment by NikitaGandhi** [comment]
> > How to test any of this?
> 
> Would be testable in `dev` we will have to collect sample notebooks from [dea-notebooks](https://github.com/GeoscienceAustralia/dea-notebooks) and manually make changes and re-save them to see if we trigger any false positives. This is a huge manual test need, perhaps can delegate to rest of DEA for collaborative testing in dev.

- tested it in dev with failing to save notebooks

**Pull request merged**
